blank_issues_enabled: false
contact_links:
  - name: 🐞 Bug
    url: https://github.com/Likelion-at-SMWU-13th/Spotal-BE/issues/new?template=bug.yml
    about: 버그 제보
  - name: 🚀 Deploy
    url: https://github.com/Likelion-at-SMWU-13th/Spotal-BE/issues/new?template=deploy.yml
    about: 배포 관련 작업
  - name: ✨ Feature
    url: https://github.com/Likelion-at-SMWU-13th/Spotal-BE/issues/new?template=feature.yml
    about: 새로운 기능 추가
  - name: 🛠 Refactor
    url: https://github.com/Likelion-at-SMWU-13th/Spotal-BE/issues/new?template=refactor.yml
    about: 리팩토링
