# Generated by Django 4.2.7 on 2025-09-22 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0014_remove_place_image_url_place_photo_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', models.JSONField(default=list)),
                ('source_text', models.TextField(blank=True, default='')),
                ('model_name', models.CharField(default='text-embedding-3-small', max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='recommendations.place')),
            ],
            options={
                'db_table': 'place_embedding',
            },
        ),
    ]
